CVP_CONFIGLETS:


CVP_DEVICES:
  leaf1-DC1:
    name: 'leaf1-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC1-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf2-DC1:
    name: 'leaf2-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf2-DC1-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported  
  leaf3-DC1:
    name: 'leaf3-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf3-DC1-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf4-DC1:
    name: 'leaf4-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'leaf4-DC1-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported
  borderleaf1-DC1:
    name: 'borderleaf1-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf1-DC1-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  borderleaf2-DC1:
    name: 'borderleaf2-DC1'
    parentContainerName: Leaf-DC1
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf2-DC1-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported      
  spine1-DC1:
    name: 'spine1-DC1'
    parentContainerName: Spine-DC1
    configlets:
        - 'ATD-INFRA'
        - 'spine1-DC1-BASE'
    imageBundle: []  # Not yet supported  
  spine2-DC1:
    name: 'spine2-DC1'
    parentContainerName: Spine-DC1
    configlets:
        - 'ATD-INFRA'
        - 'spine2-DC1-BASE'
    imageBundle: []  # Not yet supported  
  spine3-DC1:
    name: 'spine3-DC1'
    parentContainerName: Spine-DC1
    configlets:
        - 'ATD-INFRA'
        - 'spine3-DC1-BASE'
    imageBundle: []  # Not yet supported
  leaf1-DC2:
    name: 'leaf1-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC2-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf2-DC2:
    name: 'leaf2-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf2-DC2-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported  
  leaf3-DC2:
    name: 'leaf3-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf3-DC2-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  leaf4-DC2:
    name: 'leaf4-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf4-DC2-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported
  borderleaf1-DC2:
    name: 'borderleaf1-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf1-DC2-BASE'
        - 'Ansible-MLAG-Left'
    imageBundle: []  # Not yet supported  
  borderleaf2-DC2:
    name: 'borderleaf2-DC2'
    parentContainerName: Leaf-DC2
    configlets:
        - 'ATD-INFRA'
        - 'borderleaf2-DC2-BASE'
        - 'Ansible-MLAG-Right'
    imageBundle: []  # Not yet supported      
  spine1-DC2:
    name: 'spine1-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'leaf1-DC2-BASE'
    imageBundle: []  # Not yet supported  
  spine2-DC2:
    name: 'spine2-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'spine2-DC2-BASE'
    imageBundle: []  # Not yet supported  
  spine3-DC2:
    name: 'spine3-DC2'
    parentContainerName: Spine-DC2
    configlets:
        - 'ATD-INFRA'
        - 'spine3-DC2-BASE'
    imageBundle: []  # Not yet supported  
  DCI:
    name: 'DCI'
    parentContainerName: DCI
    configlets:
        - 'ATD-INFRA'
        - 'DCI-BASE'
    imageBundle: []  # Not yet supported  
